# Generated by Django 2.1.5 on 2019-02-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20190212_1347'),
        ('resume_coaching', '0002_auto_20190204_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_coaching_comment_writer', to='users.Glifer'),
            preserve_default=False,
        ),
    ]
