# Generated by Django 2.1.5 on 2019-01-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='%Y%m%d Daily Market Analysis', max_length=50)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='Daily_Market_attached_files/%Y/%m/%d/')),
                ('written_date', models.DateField(auto_now=True)),
                ('e_u_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('e_u_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('u_k_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('u_k_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fed_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fed_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('spread_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('spread_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('usyr2_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('usyr2_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('usyr10_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('usyr10_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bok_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bok_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('kryr3_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('kryr3_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('kryr10_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('kryr10_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dj_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dj_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('sp_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('sp_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('nas_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('nas_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ksp_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ksp_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ksd_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ksd_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('nik_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('nik_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('hk_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('hk_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bco_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bco_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('wti_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('wti_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('gd_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('gd_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bdi_cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bdi_ch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Daily_Market_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
