# Generated by Django 2.1.5 on 2019-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Daily Market Analysis', max_length=50),
        ),
    ]
