# Generated by Django 2.1.5 on 2019-01-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_market', '0002_auto_20190121_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attached_file',
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Daily_Market_writer', to='users.Glifer'),
        ),
    ]
