# Generated by Django 2.1.5 on 2019-01-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_market', '0004_auto_20190130_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='20190130 Daily Market Analysis', max_length=50),
        ),
    ]
