# Generated by Django 2.1.5 on 2019-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name_en',
            field=models.CharField(default='ghost', max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name_kr',
            field=models.CharField(default='유령', max_length=250),
        ),
    ]
