# Generated by Django 2.1.5 on 2019-01-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='self_intro',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='year_in_school',
        ),
    ]
