# Generated by Django 2.1.5 on 2019-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(default='010-0000-0000', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='self_intro',
            field=models.TextField(default='self introduction', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_in_school',
            field=models.CharField(choices=[('OB', 'OB'), ('1기', '1기'), ('2기', '2기'), ('3기', '3기'), ('4기', '4기')], default='4기', max_length=2),
        ),
    ]
