# Generated by Django 2.1.5 on 2019-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190114_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.FileField(default='https://via.placeholder.com/16', upload_to=''),
            preserve_default=False,
        ),
    ]
