# Generated by Django 2.1.5 on 2019-01-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190114_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_en', models.CharField(max_length=250)),
                ('name_kr', models.CharField(max_length=250)),
                ('birthdate', models.DateField(default='2000-01-01')),
                ('phonenumber', models.CharField(max_length=250)),
                ('self_intro', models.TextField(max_length=1000)),
                ('workplace', models.CharField(max_length=250)),
                ('profile_img', models.FileField(upload_to='profiles/%Y/%m/%d/')),
                ('nth', models.CharField(choices=[('OB', 'OB'), ('1기', '1기'), ('2기', '2기'), ('3기', '3기'), ('4기', '4기')], default='OB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_en', models.CharField(max_length=250)),
                ('name_kr', models.CharField(max_length=250)),
                ('birthdate', models.DateField(default='2000-01-01')),
                ('phonenumber', models.CharField(max_length=250)),
                ('self_intro', models.TextField(max_length=1000)),
                ('profile_img', models.FileField(upload_to='profiles/%Y/%m/%d/')),
                ('nth', models.CharField(choices=[('OB', 'OB'), ('1기', '1기'), ('2기', '2기'), ('3기', '3기'), ('4기', '4기')], default='4기', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name_kr',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='self_intro',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('mentor', 'mentor'), ('student', 'student'), ('applicant', 'applicant')], default='student', max_length=20),
        ),
    ]
