# Generated by Django 2.1.5 on 2019-01-25 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190124_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glifer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_mentor', models.BooleanField(default=False)),
                ('name_en', models.CharField(max_length=250)),
                ('name_kr', models.CharField(max_length=250)),
                ('birthdate', models.DateField(default='2000-01-01')),
                ('phonenumber', models.CharField(max_length=250)),
                ('self_intro', models.TextField(max_length=1000)),
                ('profile_img', models.FileField(upload_to='profiles/%Y/%m/%d/')),
                ('nth', models.CharField(choices=[('OB', 'OB'), ('1기', '1기'), ('2기', '2기'), ('3기', '3기'), ('4기', '4기')], default='4기', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_glifer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
