# Generated by Django 2.1.5 on 2019-01-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190125_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='glifer',
            name='work_at',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
