# Generated by Django 2.1.5 on 2019-01-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_glifer_work_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Asset Pricing', 'Asset Pricing'), ('Financial Economics', 'Financial Economics'), ('Financial Derivatives', 'Financial Derivatives'), ('Money and Banking', 'Money and Banking'), ('Financial Management(재무관리)', 'Financial Management(재무관리)'), ('Introduction to Financial Accounting(회계원리)', 'Introduction to Financial Accounting(회계원리)')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='extra',
            field=models.TextField(default='extra', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='futureplan',
            field=models.TextField(default='futureplan', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='glifmotive',
            field=models.TextField(default='glifmotive', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='grad',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='millitary',
            field=models.CharField(default='military', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='name_kr',
            field=models.CharField(default='namekr', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='phonenumber',
            field=models.CharField(default='ph', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='schyr',
            field=models.CharField(choices=[('1학년 1학기', '1학년 1학기'), ('1학년 2학기', '1학년 2학기'), ('2학년 1학기', '2학년 1학기'), ('2학년 2학기', '2학년 2학기'), ('3학년 1학기', '3학년 1학기'), ('3학년 2학기', '3학년 2학기'), ('4학년 1학기', '4학년 1학기'), ('4학년 2학기', '4학년 2학기'), ('기타', '기타')], default='2학년 2학기', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='stu_id',
            field=models.CharField(default='2014', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='testprep',
            field=models.CharField(default='te', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='willyou',
            field=models.CharField(default='wi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glifer',
            name='email',
            field=models.EmailField(default='email@com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='havetaken_courses',
            field=models.ManyToManyField(related_name='havetaken_courses_applicant', to='users.Subject'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='willtake_courses',
            field=models.ManyToManyField(related_name='willtake_courses_applicant', to='users.Subject'),
        ),
    ]
