# Generated by Django 2.1.5 on 2019-01-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190126_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glifer',
            name='profile_img',
            field=models.FileField(blank=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
