# Generated by Django 2.1.5 on 2019-01-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190128_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glifer',
            name='profile_img',
            field=models.FileField(upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
