# Generated by Django 2.1.5 on 2019-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190128_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glifer',
            name='profile_img',
            field=models.FileField(default='/users/man-user.png', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
