# Generated by Django 2.1.5 on 2019-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190128_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='havetaken_courses',
            field=models.ManyToManyField(blank=True, related_name='havetaken_courses_applicant', to='users.Subject'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='willtake_courses',
            field=models.ManyToManyField(blank=True, related_name='willtake_courses_applicant', to='users.Subject'),
        ),
    ]
