# Generated by Django 2.1.5 on 2019-01-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190129_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='grad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
