# Generated by Django 2.1.5 on 2019-01-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20190129_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='glifer',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
