# Generated by Django 2.1.5 on 2019-02-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190203_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='glifer',
            name='nth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Nth'),
        ),
    ]
