# Generated by Django 2.1.5 on 2019-02-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20190204_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glifer',
            name='nth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Nth'),
        ),
    ]
