# Generated by Django 2.1.5 on 2019-02-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_glifer_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='glifer',
            name='self_intro_add',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
