# Generated by Django 2.1.5 on 2019-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_glifer_self_intro_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='glifer',
            name='career',
            field=models.ManyToManyField(blank=True, to='users.Career'),
        ),
    ]
