# Generated by Django 2.1.5 on 2019-02-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20190212_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='glifer',
            name='career_cur_detail',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='glifer',
            name='career_prev_1_detail',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='glifer',
            name='career_prev_2_detail',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
