# Generated by Django 2.1.5 on 2019-01-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='announcement_attached_files/%Y/%m/%d/'),
        ),
    ]
