# Generated by Django 2.1.5 on 2019-01-16 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_auto_20190116_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Post',
        ),
    ]
