# Generated by Django 2.1.5 on 2019-01-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20190116_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
