# Generated by Django 2.1.5 on 2019-01-17 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0005_auto_20190117_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnouncementPost',
            new_name='Post',
        ),
    ]
