# Generated by Django 2.1.5 on 2019-01-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_auto_20190121_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
