# Generated by Django 2.1.5 on 2019-01-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Daily News Clipping', max_length=50)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='Daily_News_Clipping/%Y/%m/%d/')),
                ('written_date', models.DateField(auto_now=True)),
                ('news_type', models.CharField(choices=[(1, 'WSJ'), (2, 'FT'), (3, 'BB')], max_length=10)),
                ('content_1_kr', models.TextField(max_length=5000)),
                ('content_2_kr', models.TextField(max_length=5000)),
                ('content_3_kr', models.TextField(max_length=5000)),
                ('content_1_en', models.TextField(max_length=5000)),
                ('content_2_en', models.TextField(max_length=5000)),
                ('content_3_en', models.TextField(max_length=5000)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Daily_News_Clipping_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
