# Generated by Django 2.1.5 on 2019-01-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attached_file',
        ),
        migrations.AlterField(
            model_name='post',
            name='news_type',
            field=models.CharField(choices=[('wsj', 'WSJ'), ('ft', 'FT'), ('bb', 'BB')], max_length=10),
        ),
    ]
