# Generated by Django 2.1.5 on 2019-01-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_news', '0002_auto_20190121_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='2019-01-21Daily News Clipping', max_length=50),
        ),
    ]
