# Generated by Django 2.1.5 on 2019-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_news', '0004_auto_20190121_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='20190121 Daily News Clipping', max_length=50),
        ),
    ]
