# Generated by Django 2.1.5 on 2019-01-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_news', '0006_auto_20190121_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='20190128 Daily News Clipping', max_length=50),
        ),
    ]
