# Generated by Django 2.1.5 on 2019-02-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_news', '0010_auto_20190130_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='20190204 Daily News Clipping', max_length=50),
        ),
    ]
